earthquake_queries = [
    "What is an earthquake and how does it occur?",
    "What causes earthquakes to happen?",
    "How are earthquakes measured?",
    "What is the Richter scale used for?",
    "What are tectonic plates and how do they relate to earthquakes?",
    "What is the difference between magnitude and intensity?",
    "How do aftershocks differ from the main earthquake?",
    "What are the signs that an earthquake might occur?",
    "Can animals sense earthquakes before they happen?",
    "How do I know if my area is earthquake-prone?",
    "What should I do during an earthquake?",
    "What are the safest places to take cover during an earthquake?",
    "What should I avoid doing during an earthquake?",
    "How do I prepare my home for an earthquake?",
    "What items should be in an earthquake emergency kit?",
    "How do I create an earthquake evacuation plan for my family?",
    "What should I do if I’m in a classroom during an earthquake?",
    "How do schools prepare for earthquake emergencies?",
    "What should I do if I’m in a college hostel during an earthquake?",
    "How do I protect my pets during an earthquake?",
    "What are the do’s and don’ts during an earthquake?",
    "How do I stay safe if I live in a hilly area?",
    "What should I do if I’m stuck outside during an earthquake?",
    "How do I protect important documents during an earthquake?",
    "What foods should I store for earthquake emergencies?",
    "How do I keep my phone charged during a power outage?",
    "What should I do if my building starts shaking?",
    "How do I know when it’s safe to return home?",
    "What precautions should I take after an earthquake?",
    "How do I disinfect water after an earthquake?",
    "What are common injuries during earthquakes and how to treat them?",
    "How do I support friends emotionally after an earthquake?",
    "What should I do if my earthquake shelter is full?",
    "How do I help elderly neighbors evacuate safely?",
    "What are the risks of landslides in hilly areas during earthquakes?",
    "How do I secure windows and doors before an earthquake?",
    "What should I do if I’m in a moving vehicle during an earthquake?",
    "How do I protect electronics from earthquake damage?",
    "What are the emergency numbers I should save?",
    "How do I prepare my college dorm for earthquake safety?",
    "What should I teach kids about earthquake safety?",
    "How do I help someone with a disability during an earthquake?",
    "What should I do if I lose communication during an earthquake?",
    "How do I find earthquake relief centers near me?",
    "What apps send real-time earthquake alerts?",
    "How do I prepare my vehicle for evacuation?",
    "What should I do if my classroom ceiling starts cracking?",
    "How do I stay informed if the internet goes down?",
    "What are the signs of post-earthquake trauma?",
    "How do I clean up safely after an earthquake?",
    "What should I do if my house is damaged?",
    "How do I report earthquake damage?",
    "What should I do if my pet goes missing during an earthquake?",
    "How do I protect livestock during an earthquake?",
    "What are the safest places in a school building during an earthquake?",
    "How do I prepare mentally for earthquake emergencies?",
    "What should I do if I’m alone during an earthquake?",
    "How do I protect my rooftop water tank?",
    "What should I do if my college campus is under earthquake alert?",
    "How do I help classmates during an earthquake evacuation?",
    "What are the risks of staying in high-rise buildings?",
    "How do I protect glass windows in classrooms?",
    "What should I do if my school bus is caught in an earthquake?",
    "How do I prepare my hostel room for earthquake safety?",
    "What should I do if my building’s power fails?",
    "How do I keep children calm during an earthquake?",
    "What should I do if I hear conflicting earthquake information?",
    "How do I protect myself from falling debris?",
    "What should I do if I feel unsafe in my current shelter?",
    "How do I check if my house is structurally safe?",
    "What should I do if my earthquake shelter lacks supplies?",
    "How do I help clean up debris safely?",
    "What should I do if my college loses power?",
    "How do I protect school supplies from water damage?",
    "What should I do if my pet is scared during an earthquake?",
    "How do I prepare my hilltop home for earthquake safety?",
    "What should I do if I’m traveling during an earthquake?",
    "How do I stay safe in a mountain resort during an earthquake?",
    "What should I do if my school is used as a shelter?",
    "How do I help teachers manage students during an earthquake?",
    "What should I do if my family is in another city?",
    "How do I prepare my apartment for earthquake safety?",
    "What should I do if my college exams are scheduled during an earthquake?",
    "How do I protect classroom electronics?",
    "What should I do if I’m in a temporary shelter?",
    "How do I help someone who’s injured during an earthquake?",
    "What should I do if my building’s elevator stops working?",
    "How do I prepare my hill station business for earthquake impact?",
    "What should I do if my pet refuses to evacuate?",
    "How do I protect books and study materials?",
    "What should I do if I’m in a crowded shelter?",
    "How do I prepare my school bag for earthquake emergencies?",
    "What should I do if my college hostel is damaged?",
    "How do I help classmates with anxiety during an earthquake?",
    "What should I do if my family is unreachable?",
    "How do I protect my bicycle or scooter?",
    "What should I do if my school has no earthquake protocol?",
    "How do I prepare my hillside café for earthquake season?",
    "What should I do if my college library is damaged?",
    "How do I help clean up my classroom after an earthquake?",
    "What should I do if my pet needs medical help?",
    "How do I stay safe in an earthquake-prone hilly town?",
    "What should I do if my school is closed due to earthquake?",
    "How do I prepare my family for earthquake drills?",
    "What should I do if my college hostel lacks emergency supplies?",
    "How do I protect my home from earthquake damage?",
    "What should I do if I’m in a lift during an earthquake?",
    "How do I prepare my building’s foundation for earthquakes?",
    "What should I do if my school building is old and unsafe?",
    "How do I protect myself if I’m in a crowded auditorium?",
    "What should I do if my college has no evacuation plan?",
    "How do I help someone who’s unconscious after an earthquake?",
    "What should I do if my classroom furniture is unstable?",
    "How do I prepare my hilltop school for earthquake safety?",
    "What should I do if my pet is trapped in rubble?",
    "How do I protect my family’s health after an earthquake?",
    "What should I do if I’m in a hospital during an earthquake?",
    "How do I prepare my college lab for earthquake safety?",
    "What should I do if my school’s emergency exit is blocked?",
    "How do I help someone having a panic attack during an earthquake?",
    "What should I do if my building’s staircase is damaged?",
    "How do I prepare my hill village for earthquake response?",
    "What should I do if my college hostel has structural cracks?",
    "How do I protect myself if I’m in a basement during an earthquake?",
    "What should I do if my school roof collapses?",
    "How do I prepare my family’s health kit for earthquake emergencies?",
    "What should I do if my college has no first aid supplies?",
    "How do I help someone with asthma during an earthquake?",
    "What should I do if my classroom has broken glass?",
    "How do I prepare my hilltop resort for earthquake safety?",
    "What should I do if my school’s water supply is disrupted?",
    "How do I protect myself if I’m in a crowded market?",
    "What should I do if my college hostel is overcrowded?",
    "How do I prepare my family’s emergency contact list?",
    "What should I do if my school’s communication system fails?",
    "How do I help someone who’s lost their belongings?",
    "What should I do if my college has no backup power?",
    "How do I prepare my hill community for earthquake drills?"
]
# flood_queries.py

flood_queries = [
    "What is a flood and how does it occur?",
    "What causes rivers to overflow during floods?",
    "How does urbanization increase flood risk?",
    "What are flash floods and how are they different?",
    "How do I know if my area is flood-prone?",
    "What are the early warning signs of a flood?",
    "How do I receive flood alerts in my region?",
    "What should I do when a flood warning is issued?",
    "How can I prepare my house for flood season?",
    "What items should be in a flood emergency kit?",
    "How do I create a flood evacuation plan for my family?",
    "Where can I find the nearest flood shelter?",
    "What are the safest places to stay during a flood?",
    "How do I protect my pets during a flood?",
    "What should I do if I’m at school when flooding starts?",
    "How do schools prepare for flood emergencies?",
    "What are the do’s and don’ts during a flood?",
    "How do I stay safe if I live near a river?",
    "What should I avoid doing during a flood?",
    "How do I help someone who is panicking during a flood?",
    "What should I do if I get separated from my family?",
    "How do I protect important documents during a flood?",
    "What foods should I store for flood emergencies?",
    "How do I keep my phone charged during a power outage?",
    "What should I do if my house starts flooding?",
    "How do I know when it’s safe to return home?",
    "What precautions should I take after a flood?",
    "How do I disinfect water after a flood?",
    "What diseases are common after floods?",
    "How do I treat minor injuries during a flood?",
    "How do I support friends emotionally after a flood?",
    "What should I do if my flood shelter is full?",
    "How do I help elderly neighbors evacuate safely?",
    "What are the risks of staying near a swollen river?",
    "How do I secure windows and doors before a flood?",
    "What should I do if I’m stuck outside during a flood?",
    "How do I protect electronics from flood damage?",
    "What emergency numbers should I save before flood season?",
    "How do I prepare my college dorm for flood safety?",
    "What should I teach kids about flood safety?",
    "How do I help someone with a disability during a flood?",
    "What should I do if I lose communication during a flood?",
    "How do I find flood relief centers near me?",
    "What apps send real-time flood alerts?",
    "How do I prepare my vehicle for flood evacuation?",
    "What should I do if my classroom floods?",
    "How do I stay informed if the internet goes down?",
    "What are the signs of post-flood trauma?",
    "How do I clean up safely after a flood?",
    "What should I do if my house is damaged by floodwater?",
    "How do I report flood damage?",
    "What should I do if my pet goes missing during a flood?",
    "How do I protect livestock during a flood?",
    "What are the safest places in a school building during a flood?",
    "How do I prepare mentally for flood emergencies?",
    "What should I do if I’m alone during a flood?",
    "How do I protect my rooftop water tank from contamination?",
    "What should I do if my college campus is under flood alert?",
    "How do I help classmates during a flood evacuation?",
    "What are the risks of staying in low-lying buildings?",
    "How do I protect glass windows in classrooms?",
    "What should I do if my school bus is caught in floodwaters?",
    "How do I prepare my hostel room for flood safety?",
    "What should I do if my building’s power fails during a flood?",
    "How do I keep children calm during a flood?",
    "What should I do if I hear conflicting flood information?",
    "How do I protect myself from contaminated water?",
    "What should I do if I feel unsafe in my current shelter?",
    "How do I check if my house is structurally safe after a flood?",
    "What should I do if my flood shelter lacks basic supplies?",
    "How do I help clean up debris safely after a flood?",
    "What should I do if my college loses power during a flood?",
    "How do I protect school supplies from water damage?",
    "What should I do if my pet is scared during a flood?",
    "How do I prepare my riverside home for flood season?",
    "What should I do if I’m traveling during a flood alert?",
    "How do I stay safe in a boat during flood conditions?",
    "What should I do if my school is used as a flood shelter?",
    "How do I help teachers manage students during a flood?",
    "What should I do if my family is in another city during a flood?",
    "How do I prepare my apartment for flood safety?",
    "What should I do if my college exams are scheduled during a flood?",
    "How do I protect classroom electronics from flood damage?",
    "What should I do if I’m in a temporary shelter?",
    "How do I help someone who’s injured during a flood?",
    "What should I do if my building’s elevator stops working?",
    "How do I prepare my riverside business for flood impact?",
    "What should I do if my pet refuses to evacuate?",
    "How do I protect books and study materials from flood damage?",
    "What should I do if I’m in a crowded shelter?",
    "How do I prepare my school bag for flood emergencies?",
    "What should I do if my college hostel is flooded?",
    "How do I help classmates with anxiety during a flood?",
    "What should I do if my family is unreachable during a flood?",
    "How do I protect my bicycle or scooter from flood damage?",
    "What should I do if my school has no flood protocol?",
    "How do I prepare my riverside café for flood season?",
    "What should I do if my college library is damaged by flood?",
    "How do I help clean up my classroom after a flood?",
    "What should I do if my pet needs medical help during a flood?",
    "How do I stay safe in a flood-prone riverside town?",
    "What should I do if my school is closed due to flooding?",
    "How do I prepare my family for flood drills?",
    "What should I do if my college hostel lacks emergency supplies?",
    "How do I protect my home from rising water levels?",
    "What should I do if I’m in a lift during a flood?",
    "How do I prepare my building’s foundation for flood resistance?",
    "What should I do if my school building is old and flood-prone?",
    "How do I protect myself if I’m in a crowded auditorium during a flood?",
    "What should I do if my college has no evacuation plan?",
    "How do I help someone who’s unconscious after a flood?",
    "What should I do if my classroom furniture is floating?",
    "How do I prepare my riverside school for flood safety?",
    "What should I do if my pet is trapped in rising water?",
    "How do I protect my family’s health after a flood?",
    "What should I do if I’m in a hospital during a flood?",
    "How do I prepare my college lab for flood safety?",
    "What should I do if my school’s emergency exit is blocked?",
    "How do I help someone having a panic attack during a flood?",
    "What should I do if my building’s staircase is underwater?",
    "How do I prepare my river village for flood response?",
    "What should I do if my college hostel has structural cracks?",
    "How do I protect myself if I’m in a basement during a flood?",
    "What should I do if my school roof collapses during a flood?",
    "How do I prepare my family’s health kit for flood emergencies?",
    "What should I do if my college has no first aid supplies?",
    "How do I help someone with asthma during a flood?",
    "What should I do if my classroom has standing water?",
    "How do I prepare my riverside resort for flood safety?",
    "What should I do if my school’s water supply is disrupted?",
    "How do I protect myself if I’m in a crowded market during a flood?",
    "What should I do if my college hostel is overcrowded?",
    "How do I prepare my family’s emergency contact list for floods?",
    "What should I do if my school’s communication system fails?",
    "How do I help someone who’s lost their belongings in a flood?",
    "What should I do if my college has no backup power?",
    "How do I prepare my river community for flood drills?"
]
# fire_queries.py

fire_queries = [
    "What is fire and how does it start?",
    "What are the common causes of fire in homes?",
    "How do electrical fires occur?",
    "What is a forest fire and how does it spread?",
    "What should I do when a fire alarm goes off?",
    "How do I evacuate safely during a fire?",
    "What items should be in a fire emergency kit?",
    "How do I create a fire escape plan for my family?",
    "What are the do’s and don’ts during a fire emergency?",
    "How do I use a fire extinguisher properly?",
    "What are the different types of fire extinguishers?",
    "How do I know which fire extinguisher to use?",
    "What should I do if someone gets burned?",
    "How do I treat minor burns at home?",
    "What are the signs of smoke inhalation?",
    "How do I protect pets during a fire?",
    "What should I do if my pet is trapped in a burning building?",
    "How do schools prepare for fire emergencies?",
    "What should I do if I’m in a classroom during a fire?",
    "How do I help classmates evacuate during a fire?",
    "What should I do if I’m in a college hostel during a fire?",
    "How do I protect important documents from fire damage?",
    "What are the safest places to shelter during a fire?",
    "How do I stay calm during a fire evacuation?",
    "What should I do if I’m trapped in a burning building?",
    "How do I signal for help if I’m trapped during a fire?",
    "What should I do if my building’s fire exit is blocked?",
    "How do I help someone with a disability evacuate during a fire?",
    "What are the risks of using elevators during a fire?",
    "How do I prepare my house for fire safety?",
    "What are the fire safety rules for cooking at home?",
    "How do I prevent electrical fires in my building?",
    "What should I do if my school bus catches fire?",
    "How do I protect livestock during a farm fire?",
    "What should I do if a jungle fire is approaching my village?",
    "How do I help animals escape during a forest fire?",
    "What are the signs of a fire starting in a building?",
    "How do I report a fire emergency?",
    "What should I do if I see smoke in my apartment?",
    "How do I protect myself from toxic fumes during a fire?",
    "What are the symptoms of fire-related trauma?",
    "How do I help someone who’s unconscious during a fire?",
    "What should I do if my clothes catch fire?",
    "How do I stop, drop, and roll correctly?",
    "What should I do if my college has no fire evacuation plan?",
    "How do I prepare my classroom for fire safety?",
    "What should I do if my school’s fire alarm doesn’t work?",
    "How do I help someone having a panic attack during a fire?",
    "What should I do if my building’s staircase is filled with smoke?",
    "How do I prepare my village for fire drills?",
    "What should I do if my college hostel has no fire extinguishers?",
    "How do I protect myself if I’m in a basement during a fire?",
    "What should I do if my school roof catches fire?",
    "How do I prepare my family’s health kit for fire emergencies?",
    "What should I do if my college has no first aid supplies?",
    "How do I help someone with asthma during a fire?",
    "What should I do if my classroom has flammable materials?",
    "How do I prepare my jungle resort for fire safety?",
    "What should I do if my school’s water supply is disrupted during a fire?",
    "How do I protect myself if I’m in a crowded market during a fire?",
    "What should I do if my college hostel is overcrowded during evacuation?",
    "How do I prepare my family’s emergency contact list for fire emergencies?",
    "What should I do if my school’s communication system fails during a fire?",
    "How do I help someone who’s lost their belongings in a fire?",
    "What should I do if my college has no backup power during a fire?",
    "How do I prepare my farm for fire prevention?",
    "What should I do if my pet is injured in a fire?",
    "How do I protect books and study materials from fire damage?",
    "What should I do if I’m in a crowded shelter during a fire?",
    "How do I prepare my school bag for fire emergencies?",
    "What should I do if my college hostel is damaged by fire?",
    "How do I help classmates with anxiety during a fire?",
    "What should I do if my family is unreachable during a fire?",
    "How do I protect my bicycle or scooter from fire damage?",
    "What should I do if my school has no fire protocol?",
    "How do I prepare my jungle café for fire season?",
    "What should I do if my college library is damaged by fire?",
    "How do I help clean up my classroom after a fire?",
    "What should I do if my pet needs medical help after a fire?",
    "How do I stay safe in a fire-prone jungle town?",
    "What should I do if my school is closed due to fire damage?",
    "How do I prepare my family for fire drills?",
    "What should I do if my college hostel lacks emergency supplies?",
    "How do I protect my home from fire hazards?",
    "What should I do if I’m in a lift during a fire?",
    "How do I prepare my building’s foundation for fire safety?",
    "What should I do if my school building is old and unsafe?",
    "How do I protect myself if I’m in a crowded auditorium during a fire?",
    "What should I do if my college has no fire extinguishers?",
    "How do I help someone who’s burned and in shock?",
    "What should I do if my classroom furniture is flammable?",
    "How do I prepare my jungle school for fire safety?",
    "What should I do if my pet is trapped in rubble after a fire?",
    "How do I protect my family’s health after a fire?",
    "What should I do if I’m in a hospital during a fire?",
    "How do I prepare my college lab for fire safety?",
    "What should I do if my school’s emergency exit is blocked?",
    "How do I help someone having breathing issues during a fire?",
    "What should I do if my building’s staircase is damaged by fire?",
    "How do I prepare my jungle village for fire response?",
    "What should I do if my college hostel has structural cracks from fire?",
    "How do I protect myself if I’m in a basement with smoke?",
    "What should I do if my school roof collapses during a fire?",
    "How do I prepare my family’s fire safety checklist?",
    "What should I do if my college has no fire alarms?",
    "How do I help someone with burns until help arrives?",
    "What should I do if my classroom has exposed wires?",
    "How do I prepare my jungle resort for fire evacuation?",
    "What should I do if my school’s fire exit is locked?",
    "How do I protect myself if I’m in a crowded train during a fire?",
    "What should I do if my college hostel is overcrowded during fire evacuation?",
    "How do I prepare my family’s emergency plan for fire?",
    "What should I do if my school’s fire drill is outdated?",
    "How do I help someone who’s lost their pet in a fire?",
    "What should I do if my college has no fire escape route?",
    "How do I prepare my farm animals for fire evacuation?",
    "What should I do if my pet is hiding during a fire?",
    "How do I protect myself from smoke in a jungle fire?",
    "What should I do if my school’s fire extinguisher is missing?",
    "How do I prepare my village for fire safety awareness?",
    "What should I do if my college hostel has no fire exit?",
    "How do I help someone who’s disoriented during a fire?",
    "What should I do if my classroom has blocked windows?",
    "How do I prepare my jungle community for fire drills?",
    "What should I do if my pet is missing after a fire?",
    "How do I protect my family’s medical supplies during a fire?",
    "What should I do if I’m in a boat during a fire emergency?",
    "How do I prepare my ambulance team for fire response?",
    "What should I do if my college has no fire safety officer?",
    "How do I help someone who’s trapped in a burning vehicle?",
    "What should I do if my school’s fire exit is obstructed?",
    "How do I prepare my jungle school for fire evacuation?",
    "What should I do if my pet is injured and hiding?",
    "How do I protect myself from heatstroke during a fire?",
    "What should I do if my college hostel has no fire signage?",
    "How do I prepare my jungle village for fire rescue coordination?"
]



cyclone_queries = [
    "What is a cyclone and how does it form?",
    "How are cyclones different from hurricanes or typhoons?",
    "What causes cyclones to intensify rapidly?",
    "How does climate change affect cyclone frequency?",
    "What are the early warning signs of a cyclone?",
    "How do I know if my area is under cyclone watch or warning?",
    "What should I do when a c    yclone alert is issued?",
    "How can I prepare my home before cyclone season?",
    "What items should be in a cyclone emergency kit?",
    "How do I create a cyclone evacuation plan for my family?",
    "Where can I find official cyclone updates and alerts?",
    "What are the safest places to shelter during a cyclone?",
    "How do I protect my pets during a cyclone?",
    "What should I do if I’m at school when a cyclone hits?",
    "How do schools prepare for cyclone emergencies?",
    "What are the do’s and don’ts during a cyclone?",
    "How do I stay safe if I live near the coast?",
    "What should I avoid doing during a cyclone?",
    "How do I help someone who is panicking during a cyclone?",
    "What should I do if I get separated from my family?",
    "How do I protect important documents during a cyclone?",
    "What foods should I store for cyclone emergencies?",
    "How do I keep my phone charged during a power outage?",
    "What should I do if my building starts flooding?",
    "How do I know when it’s safe to return home?",
    "What precautions should I take after a cyclone passes?",
    "How do I disinfect water after a cyclone?",
    "What are common injuries during cyclones and how to treat them?",
    "How do I support friends emotionally after a cyclone?",
    "What should I do if my cyclone shelter is full?",
    "How do I help elderly neighbors evacuate safely?",
    "What are the risks of staying near the beach during a cyclone?",
    "How do I secure windows and doors before a cyclone?",
    "What should I do if I’m stuck outside during a cyclone?",
    "How do I protect electronics from cyclone damage?",
    "What are the emergency numbers I should save?",
    "How do I prepare my college dorm for cyclone season?",
    "What should I teach kids about cyclone safety?",
    "How do I help someone with a disability during a cyclone?",
    "What should I do if I lose communication during a cyclone?",
    "How do I find cyclone relief centers near me?",
    "What apps send real-time cyclone alerts?",
    "How do I prepare my vehicle for evacuation?",
    "What should I do if my classroom floods?",
    "How do I stay informed if the internet goes down?",
    "What are the signs of post-cyclone trauma?",
    "How do I clean up safely after a cyclone?",
    "What should I do if my house is damaged?",
    "How do I report cyclone damage?",
    "What should I do if my pet goes missing during a cyclone?",
    "How do I protect livestock during a cyclone?",
    "What are the safest places in a school building during a cyclone?",
    "How do I prepare mentally for cyclone emergencies?",
    "What should I do if I’m alone during a cyclone?",
    "How do I protect my rooftop water tank?",
    "What should I do if my college campus is under cyclone alert?",
    "How do I help classmates during a cyclone evacuation?",
    "What are the risks of staying in high-rise buildings?",
    "How do I protect glass windows in classrooms?",
    "What should I do if my school bus is caught in a cyclone?",
    "How do I prepare my hostel room for cyclone safety?",
    "What should I do if my building’s power fails?",
    "How do I keep children calm during a cyclone?",
    "What should I do if I hear conflicting cyclone information?",
    "How do I protect myself from flying debris?",
    "What should I do if I feel unsafe in my current shelter?",
    "How do I check if my house is structurally safe?",
    "What should I do if my cyclone shelter lacks supplies?",
    "How do I help clean up debris safely?",
    "What should I do if my college loses power?",
    "How do I protect school supplies from water damage?",
    "What should I do if my pet is scared during a cyclone?",
    "How do I prepare my coastal home for cyclone season?",
    "What should I do if I’m traveling during a cyclone alert?",
    "How do I stay safe in a beach resort during a cyclone?",
    "What should I do if my school is used as a shelter?",
    "How do I help teachers manage students during a cyclone?",
    "What should I do if my family is in another city?",
    "How do I prepare my apartment for cyclone safety?",
    "What should I do if my college exams are scheduled during a cyclone?",
    "How do I protect classroom electronics?",
    "What should I do if I’m in a temporary shelter?",
    "How do I help someone who’s injured during a cyclone?",
    "What should I do if my building’s elevator stops working?",
    "How do I prepare my coastal business for cyclone impact?",
    "What should I do if my pet refuses to evacuate?",
    "How do I protect books and study materials?",
    "What should I do if I’m in a crowded shelter?",
    "How do I prepare my school bag for cyclone emergencies?",
    "What should I do if my college hostel is flooded?",
    "How do I help classmates with anxiety during a cyclone?",
    "What should I do if my family is unreachable?",
    "How do I protect my bicycle or scooter?",
    "What should I do if my school has no cyclone protocol?",
    "How do I prepare my beachside café for cyclone season?",
    "What should I do if my college library is damaged?",
    "How do I help clean up my classroom after a cyclone?",
    "What should I do if my pet needs medical help?",
    "How do I stay safe in a cyclone-prone coastal town?",
    "What should I do if my school is closed due to cyclone?",
    "How do I prepare my family for cyclone drills?",
    "What should I do if my college hostel lacks emergency supplies?"
]



def enrich_student_query(user_input):
    for query in earthquake_queries:
        if query.lower() in user_input.lower():
            return "You are asking about earthquake safety."
    for query in flood_queries:
        if query.lower() in user_input.lower():
            return "You are asking about flood safety."
    for query in fire_queries:
        if query.lower() in user_input.lower():
            return "You are asking about fire safety."
    for query in cyclone_queries:
        if query.lower() in user_input.lower():
            return "You are asking about cyclone safety."
    return "General disaster safety guidance."
